"""Unit tests for the argparse surface of __main__.

Exercises the CLI contract without subprocess spawn — subprocess smoke tests
live in ``test_integration.py`` under the ``integration`` marker.
"""
from __future__ import annotations

import pytest

from crawler.__main__ import _build_parser


def test_default_flags():
    """No-flag defaults: sources mirror ON, jobs=1, timestamp ON, etc."""
    args = _build_parser().parse_args(["/tmp/root"])
    assert args.root == "/tmp/root"
    assert args.out == "./graph.json"
    assert args.emit_sources is True
    assert args.no_timestamp is False
    assert args.jobs == 1
    assert args.verbose == 0


def test_no_emit_sources_flag_flips_default():
    """--no-emit-sources is auto-generated by BooleanOptionalAction."""
    args = _build_parser().parse_args(["/tmp/root", "--no-emit-sources"])
    assert args.emit_sources is False


def test_emit_sources_flag_explicit():
    """--emit-sources still works (same as default, but user may pass it)."""
    args = _build_parser().parse_args(["/tmp/root", "--emit-sources"])
    assert args.emit_sources is True


def test_jobs_flag_parses():
    args = _build_parser().parse_args(["/tmp/root", "--jobs", "4"])
    assert args.jobs == 4


def test_jobs_flag_default_is_one():
    args = _build_parser().parse_args(["/tmp/root"])
    assert args.jobs == 1


def test_no_timestamp_flag():
    args = _build_parser().parse_args(["/tmp/root", "--no-timestamp"])
    assert args.no_timestamp is True


def test_help_mentions_no_emit_sources(capsys):
    """Help text should spell out the opt-out flag."""
    with pytest.raises(SystemExit):
        _build_parser().parse_args(["--help"])
    out = capsys.readouterr().out
    assert "--no-emit-sources" in out
    assert "--jobs" in out
